name = "Wolke"
license = "MIT"
homepage = "https://github.com/ress997/hugo-wolke"
licenselink = "https://github.com/ress997/hugo-wolke/blob/master/LICENSE"
description = "Grid based theme for Hugo."
tags = ["blog"]
features = ["responsive", "thumbnail", "grid", "structured data", "ogp", "twitter cards"]
min_version = 0.55.0

[author]
name = "ress"
homepage = "https://x39.dev/"
